---
application:
  name: "simple-example-node"
  project: "test new project ben"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "Test for jira ticket"
  version: "10"
routers:
- name: "main-simple-example-node"
  routes:
  - application_name: "simple-example-node"
    paths:
    - "/*"
