---
application:
  name: "simple-example-node"
  project: "Test Ben"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "test-ben-database"
  version: "10"
routers:
- name: "main-simple-example-node"
  routes:
  - application_name: "simple-example-node"
    paths:
    - "/*"
